### ISSUE TITLE
Artefacts in the alps not a bug

### ISSUE THREAD

**Issue by joeyeschner** [syncpoint/terrain-rgb#7]
Hey I just stumbled upon this repository and wanted to say that the artefacts in the alps are actually intended behavior. As far as I see it the dark areas are just elevations with heights that exceed what can be stored in the green channel (I guess > ~3300m) and therefore they appear darker.

If you compare it with the official documentation you can see the same effect in the alps there: https://docs.mapbox.com/data/tilesets/reference/mapbox-terrain-dem-v1/

**Comment by ThomasHalwax** [comment]
@joeyeschner Thanks for the clarification!
