### ISSUE TITLE
DEM lookup on an embedded platform

### ISSUE THREAD

**Issue by mhaberler** [syncpoint/terrain-rgb#9]
thanks for the great tutorial!

it helped me greatly to implement https://github.com/mhaberler/embedded-DEM-lookup 

Michael

**Comment by ThomasHalwax** [comment]
Thanks Michael, I'm glad you liked it!

Thomas

**Comment by mhaberler** [comment]
meanwhile I repeated the exercise with [Protomaps](https://protomaps.com/)   https://github.com/mhaberler/embedded-protomaps

much faster than MBTiles on embedded platforms
